// Generated by gencpp from file dashan_msg/wheelSpeed.msg
// DO NOT EDIT!


#ifndef DASHAN_MSG_MESSAGE_WHEELSPEED_H
#define DASHAN_MSG_MESSAGE_WHEELSPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dashan_msg
{
template <class ContainerAllocator>
struct wheelSpeed_
{
  typedef wheelSpeed_<ContainerAllocator> Type;

  wheelSpeed_()
    : leftwheel_speed(0.0)
    , rightwheel_speed(0.0)  {
    }
  wheelSpeed_(const ContainerAllocator& _alloc)
    : leftwheel_speed(0.0)
    , rightwheel_speed(0.0)  {
  (void)_alloc;
    }



   typedef float _leftwheel_speed_type;
  _leftwheel_speed_type leftwheel_speed;

   typedef float _rightwheel_speed_type;
  _rightwheel_speed_type rightwheel_speed;




  typedef boost::shared_ptr< ::dashan_msg::wheelSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dashan_msg::wheelSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct wheelSpeed_

typedef ::dashan_msg::wheelSpeed_<std::allocator<void> > wheelSpeed;

typedef boost::shared_ptr< ::dashan_msg::wheelSpeed > wheelSpeedPtr;
typedef boost::shared_ptr< ::dashan_msg::wheelSpeed const> wheelSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dashan_msg::wheelSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dashan_msg::wheelSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dashan_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'dashan_msg': ['/home/zhishan/Dashan_demo_update/src/dashan_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dashan_msg::wheelSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dashan_msg::wheelSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dashan_msg::wheelSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9d95faf9204c76e50e85451b2bd65f4";
  }

  static const char* value(const ::dashan_msg::wheelSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9d95faf9204c76eULL;
  static const uint64_t static_value2 = 0x50e85451b2bd65f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dashan_msg/wheelSpeed";
  }

  static const char* value(const ::dashan_msg::wheelSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 leftwheel_speed\n\
float32 rightwheel_speed\n\
";
  }

  static const char* value(const ::dashan_msg::wheelSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftwheel_speed);
      stream.next(m.rightwheel_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wheelSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dashan_msg::wheelSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dashan_msg::wheelSpeed_<ContainerAllocator>& v)
  {
    s << indent << "leftwheel_speed: ";
    Printer<float>::stream(s, indent + "  ", v.leftwheel_speed);
    s << indent << "rightwheel_speed: ";
    Printer<float>::stream(s, indent + "  ", v.rightwheel_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DASHAN_MSG_MESSAGE_WHEELSPEED_H
