TrajectoryPlannerROS:
  sim_time: 5
  escape_vel: 0
  latch_xy_goal_tolerance: false
  oscillation_reset_dist: 0.05
  min_in_place_vel_theta: 1.0
  acc_lim_y: 0.0
  meter_scoring: true
  heading_lookahead: 3
  angular_sim_granularity: 0.05
  simple_attractor: false
  xy_goal_tolerance: 0.3
  acc_lim_x: 1.0
  sim_granularity: 0.05
  publish_cost_grid_pc: false
  oscillation_reset_dist: 0
  pdist_scale: 0.6
  yaw_goal_tolerance: 0.3
  heading_scoring_timestep: 0.8
  vx_samples: 8
  acc_lim_theta: 2.0
  escape_reset_dist: 0.0
  min_vel_theta: -1.0
  escape_reset_theta: 0.0
  vy_samples: 0
  vtheta_samples: 20
  occdist_scale: 0.01
  min_vel_y: 0.0
  heading_scoring: false
  holonomic_robot: false
  max_vel_y: 0.0
  dwa: true
  max_vel_x: 0.8
  min_vel_x: 0.1
  prune_plan: true
  max_vel_theta: 0.5
  gdist_scale: 0.8
recovery_behavior_enabled: true
clearing_rotation_allowed: true
controller_frequency: 5.0
DWAPlannerROS:
  min_rot_vel: -0.3
  occdist_scale: 0.01
  oscillation_reset_dist: 0
  prune_plan: true
  vx_samples: 8
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  min_vel_y: 0.0
  max_vel_y: 0.0
  latch_xy_goal_tolerance: true
  path_distance_bias: 32.0
  xy_goal_tolerance: 0.2
  min_trans_vel: 0.02
  yaw_goal_tolerance: 0.3
  penalize_negative_x: true
  sim_time: 5.0
  vy_samples: 0
  acc_lim_th: 0.42
  max_scaling_factor: 0.2
  max_vel_x: 0.8
  max_rot_vel: 0.5
  scaling_speed: 0.25
  min_vel_x: 0.05
  vtheta_samples: 20
  acc_lim_x: 2.0
  sim_granularity: 0.05
  acc_lim_y: 0.0
  goal_distance_bias: 24.0
  max_trans_vel: 0.2