footprint:
  -
    - 0.25
    - 0.32
  -
    - -0.25
    - 0.32
  -
    - -0.25
    - -0.3
  -
    - 0.25
    - -0.3
scan:
  clearing: true
  topic: scan
  marking: true
  expected_update_rate: 10.0
  sensor_frame: /scan
  data_type: LaserScan
obstacle_range: 2.5
raytrace_range: 3
footprint_padding: 0.02
inflation_radius: 0.1
min_obstacle_height: 0.0
max_obstacle_height: 0.5
observation_sources: scan