local_costmap:
   global_frame: /odom #/map #/odom
   robot_base_frame: /base_footprint
   update_frequency: 5.0 #3.0 #5.0
   publish_frequency: 5.0   #0.5 #1.0
   static_map: false
   rolling_window: true
   width: 4.0 #6.0
   height: 4.0 #6.0
   resolution: 0.05 #0.01
   transform_tolerance: 1.0
   map_type: costmap
